name: generator
description: A set of utilities for easily generating code from metadata
version: 0.0.2-alpha.2
homepage: https://github.com/matanlurey/generator
author: Matan Lurey <matanl@google.com>
dependencies:
  analyzer: any
  analysis: 
    git: https://github.com/vgordievskiy/analysis.git
  dart_builder:
    git: https://github.com/vgordievskiy/dart_builder.git
  dart_style: any
  mustache: any
  quiver: any
dev_dependencies:
  test: any
